choco install dotnetfx -y
choco install vscode -y
choco install putty -y
choco install winscp -y
choco install googlechrome -y
choco install mobaxterm -y
choco install 7zip -y
choco install git -y
choco install keepass -y
choco install keepass-keepasshttp -y